// Resolves a DCS airdromeId (see parseMission.js's buildLaunch) to a
// readable airbase name, via the per-theatre tables generated by
// server/scripts/buildAirdromeIds.js from pydcs's terrain data.

const _cache = {}      // theatre -> Promise<{ [id]: name }>
const _resolved = {}   // theatre -> { [id]: name }, once the promise settles

function loadTheatre(theatre) {
  if (!_cache[theatre]) {
    _cache[theatre] = fetch(`/airdromes/${theatre}.json`)
      .then(r => r.ok ? r.json() : {})
      .catch(() => ({}))
      .then(data => { _resolved[theatre] = data; return data })
  }
  return _cache[theatre]
}

// Kicks off the lazy load without blocking; resolves once the theatre's
// table is available.
export function preloadAirdromes(theatre) {
  if (!theatre) return Promise.resolve({})
  return loadTheatre(theatre)
}

// Sync lookup — returns null until the theatre's table has loaded.
export function getAirdromeName(theatre, id) {
  if (!theatre || id == null) return null
  const data = _resolved[theatre]
  if (!data) { loadTheatre(theatre); return null }
  return data[String(id)] ?? null
}
