'use strict'

// Regenerates runwayData.generated.js — a static require() map of every
// client/public/runways/*.json file, keyed by filename stem. esbuild can only
// bundle static require()s, so this list can't be built with a runtime
// fs.readdirSync() inside the packaged .exe; instead we scan the directory
// now, at build time, and emit literal require() lines.
//
// Run automatically by build.js before every bundle — never edit the
// generated file by hand.

const fs   = require('fs')
const path = require('path')

const RUNWAYS_DIR = path.join(__dirname, '../../../client/public/runways')
const OUT_PATH     = path.join(__dirname, 'runwayData.generated.js')

function main() {
  const files = fs.readdirSync(RUNWAYS_DIR)
    .filter(f => f.endsWith('.json'))
    .sort()

  const lines = files.map(f => {
    const stem = path.basename(f, '.json')
    return `  ${JSON.stringify(stem)}: require(${JSON.stringify('../../../client/public/runways/' + f)}),`
  })

  const contents =
    `'use strict'\n\n` +
    `// AUTO-GENERATED by genRunwayData.js — do not edit by hand.\n` +
    `module.exports = {\n${lines.join('\n')}\n}\n`

  fs.writeFileSync(OUT_PATH, contents)
  console.log(`Wrote ${files.length} runway JSON requires to ${path.relative(process.cwd(), OUT_PATH)}`)
}

main()
